Refactor our Team Compass and update onboarding documentation
2i2c-org/team-compass pull request #449
Opened 2022-06-29 10:35 UTC by choldgraf

This PR is a light refactoring of our Team Compass information with the following goals:

- Organize it so that there's a natural top-level section for everything, and information is nested under the right top-level area
- Remove outdated information
- Remove redundant information and instead cross-link to sources of truth
- Update our onboarding documentation following these principles
- Try to cut down on wordiness in general

2022-06-29 13:37 UTC, choldgraf commented
cc @jmunroe - it would be helpful to know if there's anything obvious missing here, or that could be clearer, given that you've recently experienced all of this for the first time!

2022-07-05 19:38 UTC, jmunroe requested changes
Overall this is a much better structure to the documents.  With respect to the details, I'll revisit this material again after trying to applying the recommended organizational practices but that shouldn't stop the PR from being merged.

Just one smalling formating issue as noted above to fix.

2022-07-05 19:38 UTC, jmunroe commented on about/governance.md
> +
Formatting error on the `[^consent-decision-making]` footnote. Remove newline?

2022-07-06 08:30 UTC, choldgraf commented
Thanks for the feedback @jmunroe - I've fixed the problem that you noted!

Since this PR is a re-structure, and doesn't change a ton of content so much as re-organizes it, I am going to merge this one and we can iterate in follow-up PRs since this will get out of date quickly. Maybe @jmunroe and I can have some docs brainstorms as we work through https://github.com/2i2c-org/meta/issues/337

2022-07-06 08:30 UTC, merged